### ISSUE TITLE
Looks for index.js in Android release build

### ISSUE THREAD

**Issue by myappincome** [react-component/input-number#22] opened 2016-10-14 12:43 UTC
I've built a simple android react-native app that works fine on the device when I run `react-native run-android`.

I've followed the instructions here https://facebook.github.io/react-native/docs/signed-apk-android.html to generate a signed apk.

When I try this release apk with `react-native run-android --variant=release` I get "Unfortunately, has stopped".

When I view the console logs with `adb logcat *:S ReactNative:V ReactNativeJS:V` I get the following

10-14 11:24:42.129 29039 29060 E ReactNativeJS: Requiring unknown module "./index.ios".
10-14 11:24:42.177 29039 29060 E ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
10-14 11:24:42.534 29039 29060 E ReactNativeJS: Module AppRegistry is not a registered callable module (calling unmountApplicationComponentAtRootTag)

I've traced this back to `rc-input-number`. Basically, if I remove this component the app runs fine in release mode, when I put it back in, it's the same error.

I've been using React-Native for about 3 hours, so no idea how to solve it, sorry!

**Comment by laaxlabs** [comment] 2016-12-26 21:10
Did you manage to solve this problem without removing rc-input-number?

**Comment by myappincome** [comment] 2016-12-27 09:03
I worked around it by copying everything from index.ios.js to index.android.js in node_modules. Quite a hack, but it worked.

**Comment by laaxlabs** [comment] 2016-12-27 10:07
Thanks, will do the same.

**Comment by paranoidjk** [comment] 2017-03-03 07:42
We do not come across this problem yet, it's weird, since the `index.android.js` do exist https://github.com/react-component/input-number/blob/master/src/index.android.js

pelease give us a  reproducible demo. Or you can take a look at our use case: https://github.com/ant-design/ant-design-mobile/blob/master/components/stepper/index.tsx#L2

going to close this, if you still have any further question, feel free to repoen.

**Closed by paranoidjk** 2017-03-03 07:42 UTC
